include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true

analyzer:
  language:
    strict-casts: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  errors:
    todo: ignore
    missing_return: error
    invalid_annotation_target: ignore
    deprecated_member_use: warning
